spring:
  application:
    name: twm-orchestrator-service

server:
  port: ${EUREKA_REGISTRATION_PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:2012/eureka}
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #milliseconds
        readTimeout: 10000